### ISSUE TITLE
POST /activities/{activityId}/reservation 활동 예약하기 기능

### ISSUE THREAD

**Issue by ranunclulus** [BookJamm/BE#17]
## 📝 개요
- 활동에 대한 예약을 만드는 기능을 해 보겠습니다

## ✔️ To-Do
- [ ] 활동 아이디로 특정 활동 가져오기
- [ ] 예약 데이터 request body로 받으면 그 데이터 입력한 객체 만들기
- [ ] 예약 등록하기
- [ ] FK 연결 주의하기!!

## 👀 ETC
- 참고자료 등 기타 내용 작성

**Comment by ranunclulus** [comment]
reservation table이 생성되면 바꿀 것

**Comment by eomgerm** [comment]
현재 단계에서 예약 기능 구현 필요 없음
![스크린샷 2023-07-25 14 07 47](https://github.com/BookJamm/BE/assets/52905679/e70bf508-6717-4f3b-84ff-a7af0c277057)
