### ISSUE TITLE
GET /records/{userId}/friends?friendUserId={friendId} 친구 기록 보기

### ISSUE THREAD

**Issue by 1000chw** [BookJamm/BE#18]
## 📝 개요
- userId의 친구들의 기록 보여줌
- 기록은 친구 프로필을 누르는 거 아니면 내 기록, 친구 기록 다 보임
- 친구 프로필을 눌렀을 땐 해당 친구 기록만 보여줌

## ✔️ To-Do
- [ ] userId의 친구 목록 읽어오기
- [ ] friendId가 있으면 그 친구 기록만 가져오기
- [ ] 없으면 전체 친구 기록 가져오기
- [ ] 상태가 공개인지 확인하기
- [ ] 댓글 가능 여부 반환

## 👀 ETC
- 참고자료 등 기타 내용 작성
