### ISSUE TITLE
/places/{placeId}/acrivities 활동 검색

### ISSUE THREAD

**Issue by ranunclulus** [BookJamm/BE#3]
## 📝 개요
-  placeId에 해당하는 활동들을 시간순으로 정렬해서 보여 주기

## ✔️ To-Do
- [ ] path variable 가져오기
- [ ] api 구현하기
- [ ] 에러 케이스 점검하기
- [ ] 성공했을 시에 success response
- [ ] 성공했을 시에 json에 값 담아 전송해 주기

## 👀 ETC
- 참고자료 등 기타 내용 작성
