### ISSUE TITLE
DELETE /records/:recordId/comment/:commentId

### ISSUE THREAD

**Issue by ranunclulus** [BookJamm/BE#41]
## 📝 개요
- recordId에 해당하는 record에 달린 댓글 중 commentId인 애 삭제
## ✔️ To-Do
- [ ] comment 테이블에서 삭제하기
- [ ] record에서 댓글 카운트 내리기
- [ ] http 응답 코드 200

## 👀 ETC
- 참고자료 등 기타 내용 작성
