### ISSUE TITLE
로그인, 회원가입 로직 보안

### ISSUE THREAD

**Issue by eomgerm** [BookJamm/BE#86]
## 📝 개요
- 로그인, 회원가입 로직 보안

## ✔️ To-Do
- [ ] controller try-catch 감싸기
- [ ] 응답 파라미터 유효성 확인
- [ ] 프로필 이미지 올리기

## 👀 ETC
- 참고자료 등 기타 내용 작성
