### ISSUE TITLE
GET /places/acrivities/{activityId} 활동 세부 정보 

### ISSUE THREAD

**Issue by ranunclulus** [BookJamm/BE#9]
## 📝 개요
- activityId에 해당하는 활동의 세부 정보를 보여 주는 api

## ✔️ To-Do
- [ ] 보여 줘야 하는 칼럼 내용 정리
- [ ] Activity 폴더 만들어서 정리
- [ ] activity_like 테이블이랑의 연결
- [ ] activityId가 없으면 에러 발생시키기
